// YOUTH FOOTBALL MANAGER v2.7
const API_BASE='https://youth-football-manager.vercel.app/api';
const WS_ID='11111111-1111-1111-1111-111111111111';
const STAGIONE_ID='22222222-2222-2222-2222-222222222222';
let squadraId='33333333-3333-3333-3333-333333333333',allSquadre=[],currentPage='dashboard',allPlayers=[],allMatches=[];

document.addEventListener('DOMContentLoaded',()=>{setupNavigation();setupMobileMenu();loadSquadre().then(()=>loadDashboard());loadWorkspaceInfo();});
function setupNavigation(){document.querySelectorAll('.sidebar-nav a').forEach(l=>l.addEventListener('click',e=>{e.preventDefault();document.querySelectorAll('.sidebar-nav a').forEach(x=>x.classList.remove('active'));l.classList.add('active');currentPage=l.dataset.page;navigateTo(currentPage);}));}
function setupMobileMenu(){document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));}
function navigateTo(p){document.getElementById('pageContent').innerHTML='<div class="loading"><div class="spinner"></div>Caricamento...</div>';switch(p){case'dashboard':loadDashboard();break;case'roster':loadRoster();break;case'calendar':loadCalendar();break;case'training':loadTraining();break;case'reports':loadReports();break;case'settings':loadSettings();break;default:loadDashboard();}}
async function apiFetch(u,o={}){const r=await fetch(`${API_BASE}${u}`,{headers:{'Content-Type':'application/json',...o.headers},...o});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
function getAvatarColor(n){const C=['#1A365D','#2ECC71','#E74C3C','#F39C12','#2980B9','#8E44AD','#16A085','#D35400'];let h=0;for(let i=0;i<(n||'').length;i++)h=n.charCodeAt(i)+((h<<5)-h);return C[Math.abs(h)%C.length];}
function formatDate(d){if(!d)return'';return new Date(d).toLocaleDateString('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'});}
function formatDateShort(d){if(!d)return'';return new Date(d).toLocaleDateString('it-IT');}
function formatTime(t){if(!t)return'';return t.slice(0,5);}
function createModal(title,content,footer,mW='600px'){const ex=document.getElementById('currentModal');if(ex)ex.remove();const m=document.createElement('div');m.className='modal-overlay';m.id='currentModal';m.innerHTML=`<div class="modal-content" style="max-width:${mW};"><div class="modal-header"><h2>${title}</h2><button class="modal-close-btn" id="modalCloseX">×</button></div><div class="modal-body">${content}</div>${footer?`<div class="modal-footer">${footer}</div>`:''}</div>`;document.body.appendChild(m);const close=()=>{const x=document.getElementById('currentModal');if(x)x.remove();};document.getElementById('modalCloseX').addEventListener('click',close);m.addEventListener('click',e=>{if(e.target===m)close();});window._closeModal=close;return{modal:m,closeModal:close};}
async function loadSquadre(){try{allSquadre=await apiFetch(`/stagioni/${STAGIONE_ID}/squadre`);const sel=document.getElementById('squadraSelect');if(sel){sel.innerHTML=allSquadre.map(s=>`<option value="${s.id}" ${s.id===squadraId?'selected':''}>${s.nome}</option>`).join('');sel.addEventListener('change',e=>{squadraId=e.target.value;allPlayers=[];allMatches=[];navigateTo(currentPage);});}if(allSquadre.length>0&&!allSquadre.find(s=>s.id===squadraId))squadraId=allSquadre[0].id;}catch(err){console.error(err);}}
async function loadWorkspaceInfo(){try{const w=await apiFetch('/workspaces');if(w?.length)document.getElementById('workspaceName').textContent=w[0].nome;}catch(e){document.getElementById('workspaceName').textContent='ASD Albalonga';}}
function getSquadraName(){const s=allSquadre.find(x=>x.id===squadraId);return s?s.nome:'Squadra';}
function getSquadra(){return allSquadre.find(x=>x.id===squadraId)||{};}

// ── DASHBOARD CON TOP PLAYER ──
async function loadDashboard(){
  const c=document.getElementById('pageContent');
  try{
    const[stats,players,matches,top]=await Promise.all([
      apiFetch(`/squadre/${squadraId}/statistiche`).catch(()=>({partiteGiocate:0,calciatoriInRosa:0})),
      apiFetch(`/squadre/${squadraId}/calciatori`).catch(()=>[]),
      apiFetch(`/squadre/${squadraId}/partite`).catch(()=>[]),
      apiFetch(`/squadre/${squadraId}/top-players`).catch(()=>({marcatori:[],assistmen:[],presenze:[],ammoniti:[]}))
    ]);
    allPlayers=players;allMatches=matches;
    const next=matches.filter(m=>new Date(m.data_ora)>new Date()).sort((a,b)=>new Date(a.data_ora)-new Date(b.data_ora))[0];
    const s=getSquadra();
    
    c.innerHTML=`
      <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:24px;flex-wrap:wrap;gap:12px;">
        <div><h1 class="page-title">Dashboard</h1><p class="page-subtitle">${getSquadraName()} · ${stats.partiteGiocate} partite · ${stats.calciatoriInRosa} calciatori</p></div>
        <button class="btn btn-primary" id="btnNew">+ Nuova Partita</button>
      </div>
      <div class="widgets">
        <div class="card widget"><div class="widget-icon">📊</div><div class="widget-value">${stats.partiteGiocate}</div><div class="widget-label">Partite</div></div>
        <div class="card widget"><div class="widget-icon">👥</div><div class="widget-value">${stats.calciatoriInRosa}</div><div class="widget-label">In Rosa</div></div>
      </div>
      ${next?`<div class="card" style="margin-bottom:20px;"><h3 class="section-title">⚽ Prossima Partita</h3><div style="background:#F8F9FA;border-radius:8px;padding:20px;"><div style="font-size:14px;color:var(--gray);">${formatDate(next.data_ora)}</div><div style="font-size:22px;font-weight:bold;color:var(--blue);margin:4px 0;">vs ${next.avversario}</div><span class="badge ${next.luogo==='Casa'?'badge-green':'badge-blue'}">${next.luogo}</span><span style="margin-left:8px;font-size:13px;color:var(--gray);">${next.competizione}</span></div></div>`:''}
      
      <div class="grid-2" style="margin-bottom:20px;">
        <div class="card"><h3 class="section-title">👥 Staff Tecnico</h3><div style="padding:8px 0;">${['allenatore','dirigente','preparatore_atletico','allenatore_portieri'].map(r=>`<p style="margin-bottom:4px;"><strong>${r==='allenatore'?'Allenatore':r==='dirigente'?'Dirigente':r==='preparatore_atletico'?'Prep. Atletico':'All. Portieri'}:</strong> ${s[r]||'N/D'}</p>`).join('')}</div></div>
        <div class="card"><h3 class="section-title">⚽ Top 3 Marcatori</h3>${top.marcatori?.length?top.marcatori.map((x,i)=>`<div class="top-player"><span class="top-player-rank">${['🥇','🥈','🥉'][i]}</span><div class="top-player-avatar">${x.nome?.charAt(0)||'?'}</div><span class="top-player-name">${x.nome}</span><span class="top-player-stat">${x.gol} Gol</span></div>`).join(''):'<p style="color:var(--gray);text-align:center;padding:10px;">Nessun dato</p>'}</div>
      </div>
      
      <div class="grid-2">
        <div class="card"><h3 class="section-title">🅰️ Top 3 Assist</h3>${top.assistmen?.length?top.assistmen.map((x,i)=>`<div class="top-player"><span class="top-player-rank">${['🥇','🥈','🥉'][i]}</span><div class="top-player-avatar">${x.nome?.charAt(0)||'?'}</div><span class="top-player-name">${x.nome}</span><span class="top-player-stat">${x.assist} Assist</span></div>`).join(''):'<p style="color:var(--gray);text-align:center;padding:10px;">Nessun dato</p>'}</div>
        <div class="card"><h3 class="section-title">🏃 Top 3 Presenze</h3>${top.presenze?.length?top.presenze.map((x,i)=>`<div class="top-player"><span class="top-player-rank">${['🥇','🥈','🥉'][i]}</span><div class="top-player-avatar">${x.nome?.charAt(0)||'?'}</div><span class="top-player-name">${x.nome}</span><span class="top-player-stat">${x.presenze} Pres.</span></div>`).join(''):'<p style="color:var(--gray);text-align:center;padding:10px;">Nessun dato</p>'}</div>
      </div>`;
    document.getElementById('btnNew').addEventListener('click',()=>openMatchForm());
  }catch(err){c.innerHTML=`<div class="error-box">${err.message}</div>`;}
}

// ── ROSA ──
async function loadRoster(){const c=document.getElementById('pageContent');try{allPlayers=await apiFetch(`/squadre/${squadraId}/calciatori`);renderRoster(c,allPlayers);}catch(e){c.innerHTML=`<div class="error-box">${e.message}</div>`;}}
function renderRoster(c,p){c.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:20px;flex-wrap:wrap;gap:12px;"><div><h1 class="page-title">Rosa</h1><p class="page-subtitle">${getSquadraName()} · ${p.length} calciatori</p></div><button class="btn btn-primary" id="btnAdd">+ Aggiungi</button></div><div class="roster-toolbar"><input class="search-bar" placeholder="Cerca..." id="sInput"><select class="filter-select" id="fRuolo"><option value="">Ruoli</option><option>Portiere</option><option>Difensore</option><option>Centrocampista</option><option>Attaccante</option></select><select class="filter-select" id="fStato"><option value="">Stati</option><option>Attivo</option><option>Infortunato</option></select></div><div class="roster-grid" id="rosterGrid"></div>`;document.getElementById('btnAdd').addEventListener('click',()=>openPlayerForm());document.getElementById('sInput').addEventListener('input',filterRoster);document.getElementById('fRuolo').addEventListener('change',filterRoster);document.getElementById('fStato').addEventListener('change',filterRoster);updateRosterGrid(p);}
function updateRosterGrid(p){const g=document.getElementById('rosterGrid');if(!g)return;if(!p.length){g.innerHTML='<div class="empty-state"><div class="empty-state-icon">👥</div><div class="empty-state-title">Vuoto</div></div>';return;}g.innerHTML=p.map(x=>`<div class="card player-card" data-pid="${x.id}"><div class="player-avatar" style="background:${getAvatarColor(x.nome)}">${x.nome[0]}${x.cognome[0]}</div><div class="player-info"><div class="player-name">${x.nome} ${x.cognome}</div><div class="player-role">${x.ruolo} · #${x.numeroMaglia}</div><div style="margin-top:6px;"><span class="badge ${x.stato==='Attivo'?'badge-green':'badge-red'}">${x.stato}</span></div></div></div>`).join('');g.querySelectorAll('.player-card').forEach(card=>card.addEventListener('click',()=>openPlayerForm(card.dataset.pid)));}
function filterRoster(){const s=(document.getElementById('sInput')?.value||'').toLowerCase(),r=document.getElementById('fRuolo')?.value||'',st=document.getElementById('fStato')?.value||'';let f=allPlayers;if(s)f=f.filter(p=>`${p.nome} ${p.cognome}`.toLowerCase().includes(s));if(r)f=f.filter(p=>p.ruolo===r);if(st)f=f.filter(p=>p.stato===st);updateRosterGrid(f);}
function openPlayerForm(pid=null){const p=pid?allPlayers.find(x=>x.id===pid):null;const content=`<div class="form-grid"><div class="form-group"><label>Nome</label><input id="pfN" value="${p?.nome||''}"></div><div class="form-group"><label>Cognome</label><input id="pfC" value="${p?.cognome||''}"></div><div class="form-group"><label>Data Nascita</label><input id="pfD" type="date" value="${p?.dataNascita?new Date(p.dataNascita).toISOString().split('T')[0]:''}"></div><div class="form-group"><label>Luogo</label><input id="pfL" value="${p?.luogoNascita||''}"></div><div class="form-group"><label>Ruolo</label><select id="pfR"><option>Attaccante</option><option>Centrocampista</option><option>Difensore</option><option>Portiere</option></select></div><div class="form-group"><label>N. Maglia</label><input id="pfM" type="number" value="${p?.numeroMaglia||''}"></div><div class="form-group"><label>Matricola FIGC</label><input id="pfFigc" value="${p?.matricolaFigc||''}"></div><div class="form-group"><label>Tipo Doc</label><input id="pfTD" value="${p?.tipoDocumento||''}" placeholder="Tess."></div><div class="form-group"><label>N. Doc</label><input id="pfND" value="${p?.numeroDocumento||''}"></div><div class="form-group"><label>Rilasciato</label><input id="pfRD" value="${p?.rilasciatoDa||''}" placeholder="FIGC"></div></div>`;const footer=`<button class="btn btn-secondary" onclick="window._closeModal()">Annulla</button><button class="btn btn-primary" id="saveBtn">Salva</button>`;const{closeModal}=createModal(p?'Modifica':'Nuovo',content,footer);if(p)document.getElementById('pfR').value=p.ruolo;document.getElementById('saveBtn').addEventListener('click',async()=>{const d={nome:document.getElementById('pfN').value,cognome:document.getElementById('pfC').value,dataNascita:document.getElementById('pfD').value,luogoNascita:document.getElementById('pfL').value,ruolo:document.getElementById('pfR').value,numeroMaglia:parseInt(document.getElementById('pfM').value)||1,matricolaFigc:document.getElementById('pfFigc').value,tipoDocumento:document.getElementById('pfTD').value,numeroDocumento:document.getElementById('pfND').value,rilasciatoDa:document.getElementById('pfRD').value};try{if(p)await apiFetch(`/calciatori/${p.id}`,{method:'PUT',body:JSON.stringify(d)});else await apiFetch(`/squadre/${squadraId}/calciatori`,{method:'POST',body:JSON.stringify(d)});closeModal();loadRoster();}catch(e){alert(e.message);}});}

// ── CALENDARIO ──
async function loadCalendar(){const c=document.getElementById('pageContent');try{allMatches=await apiFetch(`/squadre/${squadraId}/partite`);renderCalendar(c,allMatches);}catch(e){c.innerHTML=`<div class="error-box">${e.message}</div>`;}}
function renderCalendar(c,m){c.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:24px;flex-wrap:wrap;gap:12px;"><div><h1 class="page-title">Calendario</h1><p class="page-subtitle">${getSquadraName()} · ${m.length} partite</p></div><button class="btn btn-primary" id="btnAdd">+ Nuova</button></div><div id="matchList"></div>`;document.getElementById('btnAdd').addEventListener('click',()=>openMatchForm());updateMatchList(m);}
function updateMatchList(m){const l=document.getElementById('matchList');if(!l)return;if(!m.length){l.innerHTML='<div class="empty-state"><div class="empty-state-icon">📅</div><div class="empty-state-title">Nessuna partita</div></div>';return;}l.innerHTML=m.map(x=>`<div class="card match-card-item"><div style="flex:1;min-width:200px;"><div class="match-date">${formatDate(x.data_ora)}</div><div class="match-teams">${getSquadraName()} vs ${x.avversario}</div><div class="match-info">${x.competizione} · ${x.luogo}</div></div><div style="display:flex;align-items:center;gap:6px;flex-wrap:wrap;"><button class="btn btn-secondary btn-small btn-conv" data-mid="${x.id}">📋 Convoca</button><button class="btn btn-secondary btn-small btn-dist" data-mid="${x.id}">📄 Distinta</button><button class="btn btn-secondary btn-small btn-editm" data-mid="${x.id}">✏️</button><button class="btn btn-secondary btn-small btn-danger btn-del" data-mid="${x.id}">🗑️</button></div></div>`).join('');l.querySelectorAll('.btn-conv').forEach(b=>b.addEventListener('click',()=>openConvocation(b.dataset.mid)));l.querySelectorAll('.btn-dist').forEach(b=>b.addEventListener('click',()=>openDistinta(b.dataset.mid)));l.querySelectorAll('.btn-editm').forEach(b=>b.addEventListener('click',()=>openMatchForm(b.dataset.mid)));l.querySelectorAll('.btn-del').forEach(b=>b.addEventListener('click',()=>deleteMatch(b.dataset.mid)));}
function openMatchForm(mid=null){const m=mid?allMatches.find(x=>x.id===mid):null;const content=`<div class="form-group" style="margin-bottom:16px;"><label>Data e Ora</label><input id="mfD" type="datetime-local" value="${m?new Date(m.data_ora).toISOString().slice(0,16):''}"></div><div class="form-group" style="margin-bottom:16px;"><label>Avversario</label><input id="mfA" value="${m?.avversario||''}"></div><div class="form-group" style="margin-bottom:16px;"><label>Luogo</label><select id="mfL"><option ${m?.luogo==='Casa'?'selected':''}>Casa</option><option ${m?.luogo==='Trasferta'?'selected':''}>Trasferta</option></select></div><div class="form-group" style="margin-bottom:16px;"><label>Competizione</label><input id="mfC" value="${m?.competizione||''}"></div><div class="form-group"><label>Note</label><textarea id="mfN" rows="2">${m?.note||''}</textarea></div>`;const footer=`<button class="btn btn-secondary" onclick="window._closeModal()">Annulla</button><button class="btn btn-primary" id="saveBtn">Salva</button>`;const{closeModal}=createModal(m?'Modifica':'Nuova Partita',content,footer,'500px');document.getElementById('saveBtn').addEventListener('click',async()=>{const d={dataOra:new Date(document.getElementById('mfD').value).toISOString(),avversario:document.getElementById('mfA').value,luogo:document.getElementById('mfL').value,competizione:document.getElementById('mfC').value,note:document.getElementById('mfN').value};try{if(m)await apiFetch(`/partite/${m.id}`,{method:'PUT',body:JSON.stringify(d)});else await apiFetch(`/squadre/${squadraId}/partite`,{method:'POST',body:JSON.stringify(d)});closeModal();loadCalendar();}catch(e){alert(e.message);}});}
async function deleteMatch(id){if(confirm('Eliminare?')){await apiFetch(`/partite/${id}`,{method:'DELETE'});loadCalendar();}}

// ── CONVOCAZIONI/DISTINTA ──
async function openConvocation(mid){const match=allMatches.find(m=>m.id===mid)||{};const[conv,gioc]=await Promise.all([apiFetch(`/partite/${mid}/convocazioni`).catch(()=>[]),apiFetch(`/squadre/${squadraId}/calciatori`)]);const ids=conv.map(c=>c.calciatoreId);const content=`<p style="margin-bottom:16px;color:var(--gray);">${formatDate(match.data_ora)}</p>${gioc.map(g=>`<div class="convocation-item"><input type="checkbox" ${ids.includes(g.id)?'checked':''} data-pid="${g.id}" style="width:20px;height:20px;cursor:pointer;accent-color:var(--green);"><div class="player-avatar" style="width:32px;height:32px;font-size:12px;background:${getAvatarColor(g.nome)};">${g.nome[0]}${g.cognome[0]}</div><span style="flex:1;">${g.nome} ${g.cognome}</span><span style="color:var(--gray);font-size:13px;">${g.ruolo} · #${g.numeroMaglia}</span></div>`).join('')}`;const footer=`<button class="btn btn-secondary" onclick="window._closeModal()">Chiudi</button><button class="btn btn-primary" id="saveBtn">💾 Salva</button>`;const{closeModal}=createModal(`📋 Convocazioni - vs ${match.avversario||'...'}`,content,footer);document.getElementById('saveBtn').addEventListener('click',async()=>{for(const cb of document.querySelectorAll('#currentModal input[type=checkbox]')){await apiFetch(`/partite/${mid}/convocazioni`,{method:'POST',body:JSON.stringify({calciatoreId:cb.dataset.pid,presente:cb.checked})}).catch(()=>{});}closeModal();alert('✅ Salvate!');});}
async function openDistinta(mid){const content='<div id="distintaInner"><div class="loading"><div class="spinner"></div>Caricamento...</div></div>';const footer=`<button class="btn btn-secondary" onclick="window._closeModal()">Chiudi</button><button class="btn btn-primary" id="printBtn">🖨️ Stampa</button>`;createModal('📄 Distinta Gara',content,footer,'950px');document.getElementById('printBtn').addEventListener('click',()=>{const el=document.getElementById('distintaInner');if(el){const w=window.open('','_blank','width=1000,height=800');w.document.write(`<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Distinta</title><style>@page{margin:8mm;size:A4 portrait}body{font-family:'Courier New',monospace;font-size:12px;margin:0;padding:10mm}.distinta-header{text-align:center;margin-bottom:20px}h2{font-size:16px}h3{font-size:14px}.distinta-table{width:100%;border-collapse:collapse}.distinta-table th,.distinta-table td{border:1px solid #333;padding:6px 8px;text-align:center;font-size:11px}th{background:#f0f0f0}.capitano{background:#FFF9C4}.vice{background:#E8F5E9}@media print{body{padding:0}}</style></head><body>${el.innerHTML}<script>window.onload=function(){window.print();setTimeout(function(){window.close()},500)}<\/script></body></html>`);w.document.close();}});try{renderDistinta(await apiFetch(`/partite/${mid}/distinta`));}catch(e){document.getElementById('distintaInner').innerHTML='<div class="error-box"><p>Formazione non disponibile</p></div>';}}
function renderDistinta(d){const c=document.getElementById('distintaInner');if(!c)return;const t=d.formazione||[];if(!t.length){c.innerHTML='<div class="empty-state"><div class="empty-state-icon">📋</div><div class="empty-state-title">Nessun giocatore</div></div>';return;}const dt=new Date(d.partita.dataOra);c.innerHTML=`<div class="distinta"><div class="distinta-header"><h2>DISTINTA DEI PARTECIPANTI ALLA GARA</h2><h3>${d.societa} - ${d.partita.avversario}</h3><p><strong>Campionato:</strong> ${d.partita.competizione}</p><p><strong>Data:</strong> ${dt.toLocaleDateString('it-IT')} · <strong>Ore:</strong> ${dt.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}</p><p><strong>Luogo:</strong> ${d.partita.luogo==='Casa'?'Casa':'Trasferta'}</p></div><table class="distinta-table"><thead><tr><th>N.</th><th>Data Nascita</th><th>Cognome e Nome</th><th>Cap/V.Cap</th><th>Matricola FIGC</th><th colspan="3">Documento</th><th>Esp.</th><th>Amm.</th></tr><tr><th></th><th></th><th></th><th></th><th></th><th>Tipo</th><th>Numero</th><th>Rilasciato</th><th></th><th></th></tr></thead><tbody>${t.map(f=>`<tr class="${f.capitano?'capitano':f.viceCapitano?'vice':''}"><td>${f.numeroMaglia||'-'}</td><td>${f.dataNascita?formatDateShort(f.dataNascita):'-'}</td><td style="text-align:left;">${f.cognome||''} ${f.nome||''}</td><td>${f.capitano?'CAP':f.viceCapitano?'V.CAP':''}</td><td>${f.matricolaFigc||'-'}</td><td>${f.tipoDocumento||'-'}</td><td>${f.numeroDocumento||'-'}</td><td>${f.rilasciatoDa||'-'}</td><td></td><td></td></tr>`).join('')}</tbody></table></div>`;}

// ── ALLENAMENTI CON RICERCA PER DATA ──
async function loadTraining(){
  const c=document.getElementById('pageContent');
  try{
    const[config,presenze,giocatori,summary]=await Promise.all([
      apiFetch(`/squadre/${squadraId}/allenamenti/config`).catch(()=>[]),
      apiFetch(`/squadre/${squadraId}/allenamenti/presenze`).catch(()=>[]),
      apiFetch(`/squadre/${squadraId}/calciatori`).catch(()=>[]),
      apiFetch(`/squadre/${squadraId}/allenamenti/summary`).catch(()=>({}))
    ]);
    allPlayers=giocatori;renderTraining(c,config,presenze,giocatori,summary);
  }catch(e){c.innerHTML=`<div class="error-box">${e.message}</div>`;}
}

function renderTraining(c,config,presenze,giocatori,summary){
  const giorni=['Dom','Lun','Mar','Mer','Gio','Ven','Sab'];
  const oggi=new Date().toISOString().split('T')[0];
  
  // Date uniche dalle presenze per il selettore
  const dateUniche=[...new Set(presenze.map(p=>p.data))].sort().reverse();
  
  c.innerHTML=`
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:24px;flex-wrap:wrap;gap:12px;">
      <div><h1 class="page-title">Allenamenti</h1><p class="page-subtitle">${getSquadraName()} · Presenze e configurazione</p></div>
      <button class="btn btn-primary" id="btnAdd">+ Configura</button>
    </div>
    
    <div class="grid-2" style="margin-bottom:20px;">
      <div class="card"><h3 class="section-title">📅 Settimana Tipo</h3><div id="trainConfig">${config.length===0?'<p style="color:var(--gray);">Nessun allenamento</p>':config.map(c=>`<div style="display:flex;align-items:center;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--border);"><div><strong>${giorni[c.giorno_settimana]}</strong> · ${formatTime(c.ora_inizio)}-${formatTime(c.ora_fine)}</div><div style="font-size:13px;color:var(--gray);">${c.luogo||''}</div><button class="btn btn-secondary btn-small btn-del" data-tid="${c.id}">🗑️</button></div>`).join('')}</div></div>
      <div class="card"><h3 class="section-title">📋 Presenze Giornaliere</h3><p style="margin-bottom:8px;">Seleziona data:</p><select id="dataSelect" style="width:100%;padding:10px;border:1px solid var(--border);border-radius:8px;margin-bottom:12px;">${dateUniche.map(d=>`<option value="${d}" ${d===oggi?'selected':''}>${formatDateShort(d)}</option>`).join('')}${dateUniche.length===0?`<option>${oggi}</option>`:''}</select><p style="margin-bottom:8px;">Segna <span style="color:#E74C3C;font-weight:600;">ASSENTE</span>:</p><div id="presenzeList">${giocatori.map(g=>{const p=presenze.find(x=>x.calciatoreId===g.id&&x.data===oggi);return`<div class="convocation-item"><input type="checkbox" ${p&&!p.presente?'checked':''} data-pid="${g.id}" style="width:20px;height:20px;cursor:pointer;accent-color:#E74C3C;"><div class="player-avatar" style="width:32px;height:32px;font-size:12px;background:${getAvatarColor(g.nome)};">${g.nome[0]}${g.cognome[0]}</div><span style="flex:1;">${g.nome} ${g.cognome}</span></div>`;}).join('')}</div><button class="btn btn-primary" id="btnSavePres" style="margin-top:12px;">💾 Salva</button></div>
    </div>
    
    <div class="card"><h3 class="section-title">📊 Riepilogo Presenze Stagionali</h3><div style="overflow-x:auto;"><table style="width:100%;border-collapse:collapse;font-size:13px;"><thead><tr style="background:#F8F9FA;"><th style="padding:8px;text-align:left;">Calciatore</th><th style="padding:8px;">Tot. Allen.</th><th style="padding:8px;color:#27AE60;">Presente</th><th style="padding:8px;color:#E74C3C;">Assente</th><th style="padding:8px;">% Presenze</th><th style="padding:8px;color:#E74C3C;">Assenti Sett.</th></tr></thead><tbody>${giocatori.map(g=>{const s=summary[g.id]||{totali:0,presenti:0,assenti:0,settimanali:0,presentiSett:0,assentiSett:0};const perc=s.totali>0?Math.round((s.presenti/s.totali)*100):0;return`<tr style="border-bottom:1px solid var(--border);"><td style="padding:8px;font-weight:500;">${g.nome} ${g.cognome}</td><td style="padding:8px;text-align:center;">${s.totali}</td><td style="padding:8px;text-align:center;color:#27AE60;">${s.presenti}</td><td style="padding:8px;text-align:center;color:#E74C3C;">${s.assenti}</td><td style="padding:8px;text-align:center;">${perc}%</td><td style="padding:8px;text-align:center;color:#E74C3C;font-weight:600;">${s.assentiSett}</td></tr>`;}).join('')}</tbody></table></div><p style="font-size:11px;color:var(--gray);margin-top:8px;">* Settimana corrente (lunedì-oggi) · % Presenze = Presenze / Totale Allenamenti</p></div>`;
  
  document.getElementById('btnAdd').addEventListener('click',()=>openTrainingForm());
  document.querySelectorAll('.btn-del').forEach(b=>b.addEventListener('click',async()=>{await apiFetch(`/allenamenti/config/${b.dataset.tid}`,{method:'DELETE'});loadTraining();}));
  
  // Aggiorna presenze quando cambia data
  document.getElementById('dataSelect').addEventListener('change',function(){const d=this.value;document.querySelectorAll('#presenzeList input[type=checkbox]').forEach(cb=>{const pid=cb.dataset.pid;const p=presenze.find(x=>x.calciatoreId===pid&&x.data===d);cb.checked=p&&!p.presente;});});
  
  document.getElementById('btnSavePres').addEventListener('click',async()=>{const d=document.getElementById('dataSelect').value;for(const cb of document.querySelectorAll('#presenzeList input[type=checkbox]')){await apiFetch(`/squadre/${squadraId}/allenamenti/presenze`,{method:'POST',body:JSON.stringify({calciatoreId:cb.dataset.pid,data:d,presente:!cb.checked,note:cb.checked?'Assente':null})}).catch(()=>{});}alert('✅ Salvate!');loadTraining();});
}

function openTrainingForm(){const giorni=['Domenica','Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato'];const content=`<div class="form-group" style="margin-bottom:16px;"><label>Giorno</label><select id="tfG">${giorni.map((g,i)=>`<option value="${i}">${g}</option>`).join('')}</select></div><div class="form-grid"><div class="form-group"><label>Inizio</label><input id="tfI" type="time"></div><div class="form-group"><label>Fine</label><input id="tfF" type="time"></div></div><div class="form-group" style="margin-top:16px;"><label>Luogo</label><input id="tfL" placeholder="Campo"></div>`;const footer=`<button class="btn btn-secondary" onclick="window._closeModal()">Annulla</button><button class="btn btn-primary" id="saveBtn">Salva</button>`;const{closeModal}=createModal('Configura Allenamento',content,footer,'500px');document.getElementById('saveBtn').addEventListener('click',async()=>{await apiFetch(`/squadre/${squadraId}/allenamenti/config`,{method:'POST',body:JSON.stringify({giorno_settimana:parseInt(document.getElementById('tfG').value),ora_inizio:document.getElementById('tfI').value,ora_fine:document.getElementById('tfF').value,luogo:document.getElementById('tfL').value})});closeModal();loadTraining();});}

// ── REPORT ──
function loadReports(){document.getElementById('pageContent').innerHTML=`<h1 class="page-title">Report</h1><p class="page-subtitle">${getSquadraName()} · In sviluppo</p>`;}

// ── IMPOSTAZIONI ──
async function loadSettings(){const c=document.getElementById('pageContent');const s=getSquadra();c.innerHTML=`<h1 class="page-title">Impostazioni</h1><p class="page-subtitle">${getSquadraName()} · Gestione</p><div class="card" style="margin-bottom:20px;"><h3 class="section-title">⚙️ Modifica</h3><div class="form-grid"><div class="form-group"><label>Nome</label><input id="sN" value="${s.nome||''}"></div><div class="form-group"><label>Categoria</label><input id="sC" value="${s.categoria||''}"></div><div class="form-group"><label>Allenatore</label><input id="sA" value="${s.allenatore||''}"></div><div class="form-group"><label>Dirigente</label><input id="sD" value="${s.dirigente||''}"></div><div class="form-group"><label>Prep. Atletico</label><input id="sP" value="${s.preparatore_atletico||''}"></div><div class="form-group"><label>All. Portieri</label><input id="sAP" value="${s.allenatore_portieri||''}"></div></div><div style="display:flex;gap:12px;margin-top:16px;"><button class="btn btn-primary" id="btnSave">💾 Salva</button><button class="btn btn-danger" id="btnDel" style="background:#E74C3C;color:white;">🗑️ Elimina</button></div></div><div class="card"><h3 class="section-title">➕ Nuova</h3><div class="form-grid"><div class="form-group"><label>Nome</label><input id="nN" placeholder="Under 15 Regionale"></div><div class="form-group"><label>Categoria</label><input id="nC" placeholder="Under 15"></div><div class="form-group"><label>Allenatore</label><input id="nA"></div><div class="form-group"><label>Dirigente</label><input id="nD"></div><div class="form-group"><label>Prep. Atletico</label><input id="nP"></div><div class="form-group"><label>All. Portieri</label><input id="nAP"></div></div><button class="btn btn-primary" id="btnNew" style="margin-top:16px;">➕ Crea</button></div>`;
  document.getElementById('btnSave').addEventListener('click',async()=>{await apiFetch(`/squadre/${squadraId}`,{method:'PUT',body:JSON.stringify({nome:document.getElementById('sN').value,categoria:document.getElementById('sC').value,allenatore:document.getElementById('sA').value,dirigente:document.getElementById('sD').value,preparatore_atletico:document.getElementById('sP').value,allenatore_portieri:document.getElementById('sAP').value})});await loadSquadre();alert('✅ Aggiornato!');loadSettings();});
  document.getElementById('btnDel').addEventListener('click',async()=>{if(!confirm(`⚠️ Eliminare ${getSquadraName()}?`))return;if(!confirm('Sei SICURO?'))return;await apiFetch(`/squadre/${squadraId}`,{method:'DELETE'});await loadSquadre();if(allSquadre.length>0){squadraId=allSquadre[0].id;navigateTo('dashboard');}else alert('Tutte eliminate.');});
  document.getElementById('btnNew').addEventListener('click',async()=>{await apiFetch(`/stagioni/${STAGIONE_ID}/squadre`,{method:'POST',body:JSON.stringify({nome:document.getElementById('nN').value,categoria:document.getElementById('nC').value,allenatore:document.getElementById('nA').value,dirigente:document.getElementById('nD').value,preparatore_atletico:document.getElementById('nP').value,allenatore_portieri:document.getElementById('nAP').value})});await loadSquadre();alert('✅ Creata!');loadSettings();});
}
